### PR TITLE
Fix/update table gsi

### PR DESCRIPTION
**Pull request by joaquinservetto**
Issue #, if available:
https://github.com/aws-controllers-k8s/community/issues/1920

Description of changes:
Fix error faced when creating a gsi for an existing table using already defined attributes. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by joaquinservetto** [comment]
Hey @a-hilaly, is there anything else missing to merge this?

**Review by a-hilaly — APPROVED** [review]
Thank you @joaquinservetto !
TIL You can reuse the same attributes to create more GSIs..
/lgtm

**Comment by a-hilaly** [comment]
@joaquinservetto Can we also add end2end tests to make sure that the table is in Synced stated?

**Pull request merged**
