### PR TITLE
Add `GlobalTable` resource custom hooks, terminalCodes and e2e tests

### PR DESCRIPTION
**Pull request by A-Hilaly**
Part of https://github.com/aws-controllers-k8s/community/issues/803

Description of changes
- Add custom hooks, terminalCodes to `GlobalTable` resource in `generator.yaml`
- Add e2e tests for `GlobalTable` create and delete operations

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
Note to reviewers: This PR needs to be rebased once #3 is merged
/hold

**Review by jaypipes — APPROVED** [review]
Excellent work on this, @A-Hilaly. `GlobalTable` is a weird resource indeed...

**Pull request merged**
